package Nav;

import javax.servlet.jsp.JspException;
import javax.servlet.jsp.JspWriter;
import javax.servlet.jsp.tagext.TagSupport;

public class DashNav extends TagSupport
{
	private String page;

    public void setPage(String page) {
        this.page = page;
    }

    public String getPage() {
        return page;
    }
    
    
  public int doStartTag() throws JspException
  {
      JspWriter out = pageContext.getOut();
      
      try
      {
    	  out.print("<head>\n"
    	  		+ "    <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.2/examples/dashboard/\">\n"
    	  		+ "	<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n"
    	  		+ "    <link href=\"css/dashboard.css\" rel=\"stylesheet\">\n"
    	  		+ "</head>");
    	  
    	  out.print("<style>\n"
    	  		+ "      .bd-placeholder-img {\n"
    	  		+ "        font-size: 1.125rem;\n"
    	  		+ "        text-anchor: middle;\n"
    	  		+ "        -webkit-user-select: none;\n"
    	  		+ "        -moz-user-select: none;\n"
    	  		+ "        user-select: none;\n"
    	  		+ "      }\n"
    	  		+ "\n"
    	  		+ "      @media (min-width: 768px) {\n"
    	  		+ "        .bd-placeholder-img-lg {\n"
    	  		+ "          font-size: 3.5rem;\n"
    	  		+ "        }\n"
    	  		+ "      }\n"
    	  		+ "\n"
    	  		+ "      .b-example-divider {\n"
    	  		+ "        height: 3rem;\n"
    	  		+ "        background-color: rgba(0, 0, 0, .1);\n"
    	  		+ "        border: solid rgba(0, 0, 0, .15);\n"
    	  		+ "        border-width: 1px 0;\n"
    	  		+ "        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);\n"
    	  		+ "      }\n"
    	  		+ "\n"
    	  		+ "      .b-example-vr {\n"
    	  		+ "        flex-shrink: 0;\n"
    	  		+ "        width: 1.5rem;\n"
    	  		+ "        height: 100vh;\n"
    	  		+ "      }\n"
    	  		+ "\n"
    	  		+ "      .bi {\n"
    	  		+ "        vertical-align: -.125em;\n"
    	  		+ "        fill: currentColor;\n"
    	  		+ "      }\n"
    	  		+ "\n"
    	  		+ "      .nav-scroller {\n"
    	  		+ "        position: relative;\n"
    	  		+ "        z-index: 2;\n"
    	  		+ "        height: 2.75rem;\n"
    	  		+ "        overflow-y: hidden;\n"
    	  		+ "      }\n"
    	  		+ "\n"
    	  		+ "      .nav-scroller .nav {\n"
    	  		+ "        display: flex;\n"
    	  		+ "        flex-wrap: nowrap;\n"
    	  		+ "        padding-bottom: 1rem;\n"
    	  		+ "        margin-top: -1px;\n"
    	  		+ "        overflow-x: auto;\n"
    	  		+ "        text-align: center;\n"
    	  		+ "        white-space: nowrap;\n"
    	  		+ "        -webkit-overflow-scrolling: touch;\n"
    	  		+ "      }\n"
    	  		+ "    </style>");
    	  
    	  out.print("<body>\n"
    	  		+ "\n"
    	  		+ "<header class=\"navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow\">\n"
    	  		+ "  <a class=\"navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6\" href=\"Dashboard.jsp\">Bombay Bank</a>\n"
    	  		+ "  <button class=\"navbar-toggler position-absolute d-md-none collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#sidebarMenu\" aria-controls=\"sidebarMenu\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
    	  		+ "    <span class=\"navbar-toggler-icon\"></span>\n"
    	  		+ "  </button>\n"
    	  		+ "  <div class=\"navbar-nav\">\n"
    	  		+ "    <div class=\"nav-item text-nowrap\">\n"
    	  		+ "      <a class=\"nav-link px-3\" href=\"Home.jsp\">Sign out</a>\n"
    	  		+ "    </div>\n"
    	  		+ "  </div>\n"
    	  		+ "</header>");
    	  
    	  out.print("<div class=\"container-fluid\">\n"
    	  		+ "  <div class=\"row\">");
    	  
    	  switch(page)
    	  {
    	  case "Dash":
    		  out.print("<nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\n"
    		  		+ "      <div class=\"position-sticky pt-3 sidebar-sticky\">\n"
    		  		+ "        <ul class=\"nav flex-column\">\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link active\" aria-current=\"page\" href=\"Dashboard.jsp\">\n"
    		  		+ "              <span data-feather=\"home\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Dashboard\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"CheckBal.jsp\">\n"
    		  		+ "              <span data-feather=\"file\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Check Balance\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Deposit.jsp\">\n"
    		  		+ "              <span data-feather=\"shopping-cart\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Deposit\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Withdraw.jsp\">\n"
    		  		+ "              <span data-feather=\"users\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Withdraw\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Transfer.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Transfer\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Password.jsp\">\n"
    		  		+ "              <span data-feather=\"layers\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Change Password\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"DeleteAcc.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Delete Account\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "        </ul>\n"
    		  		+ "\n"
    		  		+ "      </div>\n"
    		  		+ "    </nav>");
    		  break;
    	  case "Balance":
    		  out.print("<nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\n"
    		  		+ "      <div class=\"position-sticky pt-3 sidebar-sticky\">\n"
    		  		+ "        <ul class=\"nav flex-column\">\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" aria-current=\"page\" href=\"Dashboard.jsp\">\n"
    		  		+ "              <span data-feather=\"home\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Dashboard\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link active\" href=\"CheckBal.jsp\">\n"
    		  		+ "              <span data-feather=\"file\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Check Balance\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Deposit.jsp\">\n"
    		  		+ "              <span data-feather=\"shopping-cart\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Deposit\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Withdraw.jsp\">\n"
    		  		+ "              <span data-feather=\"users\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Withdraw\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Transfer.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Transfer\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Password.jsp\">\n"
    		  		+ "              <span data-feather=\"layers\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Change Password\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"DeleteAcc.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Delete Account\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "        </ul>\n"
    		  		+ "\n"
    		  		+ "      </div>\n"
    		  		+ "    </nav>");
      		  break;
    	  case "Deposit":
    		  out.print("<nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\n"
    		  		+ "      <div class=\"position-sticky pt-3 sidebar-sticky\">\n"
    		  		+ "        <ul class=\"nav flex-column\">\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" aria-current=\"page\" href=\"Dashboard.jsp\">\n"
    		  		+ "              <span data-feather=\"home\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Dashboard\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"CheckBal.jsp\">\n"
    		  		+ "              <span data-feather=\"file\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Check Balance\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link active\" href=\"Deposit.jsp\">\n"
    		  		+ "              <span data-feather=\"shopping-cart\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Deposit\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Withdraw.jsp\">\n"
    		  		+ "              <span data-feather=\"users\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Withdraw\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Transfer.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Transfer\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Password.jsp\">\n"
    		  		+ "              <span data-feather=\"layers\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Change Password\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"DeleteAcc.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Delete Account\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "        </ul>\n"
    		  		+ "\n"
    		  		+ "      </div>\n"
    		  		+ "    </nav>");
      		  break;
    	  case "Withdraw":
    		  out.print("<nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\n"
    		  		+ "      <div class=\"position-sticky pt-3 sidebar-sticky\">\n"
    		  		+ "        <ul class=\"nav flex-column\">\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" aria-current=\"page\" href=\"Dashboard.jsp\">\n"
    		  		+ "              <span data-feather=\"home\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Dashboard\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"CheckBal.jsp\">\n"
    		  		+ "              <span data-feather=\"file\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Check Balance\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Deposit.jsp\">\n"
    		  		+ "              <span data-feather=\"shopping-cart\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Deposit\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link active\" href=\"Withdraw.jsp\">\n"
    		  		+ "              <span data-feather=\"users\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Withdraw\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Transfer.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Transfer\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Password.jsp\">\n"
    		  		+ "              <span data-feather=\"layers\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Change Password\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"DeleteAcc.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Delete Account\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "        </ul>\n"
    		  		+ "\n"
    		  		+ "      </div>\n"
    		  		+ "    </nav>");
      		  break;
    	  case "Transfer":
    		  out.print("<nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\n"
    		  		+ "      <div class=\"position-sticky pt-3 sidebar-sticky\">\n"
    		  		+ "        <ul class=\"nav flex-column\">\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" aria-current=\"page\" href=\"Dashboard.jsp\">\n"
    		  		+ "              <span data-feather=\"home\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Dashboard\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"CheckBal.jsp\">\n"
    		  		+ "              <span data-feather=\"file\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Check Balance\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Deposit.jsp\">\n"
    		  		+ "              <span data-feather=\"shopping-cart\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Deposit\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Withdraw.jsp\">\n"
    		  		+ "              <span data-feather=\"users\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Withdraw\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link active\" href=\"Transfer.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Transfer\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Password.jsp\">\n"
    		  		+ "              <span data-feather=\"layers\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Change Password\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"DeleteAcc.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Delete Account\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "        </ul>\n"
    		  		+ "\n"
    		  		+ "      </div>\n"
    		  		+ "    </nav>");
      		  break;
    	  case "Password":
    		  out.print("<nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\n"
    		  		+ "      <div class=\"position-sticky pt-3 sidebar-sticky\">\n"
    		  		+ "        <ul class=\"nav flex-column\">\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" aria-current=\"page\" href=\"Dashboard.jsp\">\n"
    		  		+ "              <span data-feather=\"home\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Dashboard\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"CheckBal.jsp\">\n"
    		  		+ "              <span data-feather=\"file\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Check Balance\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Deposit.jsp\">\n"
    		  		+ "              <span data-feather=\"shopping-cart\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Deposit\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Withdraw.jsp\">\n"
    		  		+ "              <span data-feather=\"users\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Withdraw\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Transfer.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Transfer\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link active\" href=\"Password.jsp\">\n"
    		  		+ "              <span data-feather=\"layers\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Change Password\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"DeleteAcc.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Delete Account\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "        </ul>\n"
    		  		+ "\n"
    		  		+ "      </div>\n"
    		  		+ "    </nav>");
      		  break;
    	  case "Delete":
    		  out.print("<nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\n"
    		  		+ "      <div class=\"position-sticky pt-3 sidebar-sticky\">\n"
    		  		+ "        <ul class=\"nav flex-column\">\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" aria-current=\"page\" href=\"Dashboard.jsp\">\n"
    		  		+ "              <span data-feather=\"home\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Dashboard\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"CheckBal.jsp\">\n"
    		  		+ "              <span data-feather=\"file\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Check Balance\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Deposit.jsp\">\n"
    		  		+ "              <span data-feather=\"shopping-cart\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Deposit\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Withdraw.jsp\">\n"
    		  		+ "              <span data-feather=\"users\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Withdraw\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Transfer.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Transfer\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link\" href=\"Password.jsp\">\n"
    		  		+ "              <span data-feather=\"layers\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Change Password\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "          <li class=\"nav-item\">\n"
    		  		+ "            <a class=\"nav-link active\" href=\"DeleteAcc.jsp\">\n"
    		  		+ "              <span data-feather=\"bar-chart-2\" class=\"align-text-bottom\"></span>\n"
    		  		+ "              Delete Account\n"
    		  		+ "            </a>\n"
    		  		+ "          </li>\n"
    		  		+ "        </ul>\n"
    		  		+ "\n"
    		  		+ "      </div>\n"
    		  		+ "    </nav>");
      		  break;
    	  default: 
    	  }
    	  
    	  out.print("</div>\n"
    	  		+ "    </div>"
    	  		+ "</body>");
    	  
    	  out.print("<script src=\"js/bootstrap.bundle.min.js\"></script>\n"
    	  		+ "<script src=\"https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js\" integrity=\"sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE\" crossorigin=\"anonymous\"></script><script src=\"https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js\" integrity=\"sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha\" crossorigin=\"anonymous\"></script><script src=\"dashboard.js\"></script>\n");
      }
      catch(Exception e)
      {
    	  e.printStackTrace();
      }
      return SKIP_BODY;
  }

}